name: Deploy Jekyll site
on:
  push:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: bundle install

      - name: Build site
        run: |
          rm -rf _site  
          bundle exec jekyll clean
          bundle exec jekyll build

      - name: Ensure _site directory exists
        run: mkdir -p _site

      - name: Create .nojekyll file
        run: touch _site/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./_site
